const { REQUIRED_ENV } = require('./src/testUtils/env');

const CLEAN_TEST_ENV_KEYS = [
  'CORS_ORIGIN',
  'CORS_ORIGIN_LIST',
  'CORS_PUBLIC_ORIGINS',
  'CSP_DIRECTIVES',
  'REFERRER_POLICY',
  'HSTS_MAX_AGE',
  'HSTS_INCLUDE_SUBDOMAINS',
  'HSTS_PRELOAD',
  'CONFIG_DASHBOARD_ENABLED',
  'CONFIG_DASHBOARD_USER',
  'CONFIG_DASHBOARD_PASS',
  'CONFIG_DASHBOARD_ALLOWED_IPS',
  'CONFIG_DASHBOARD_KEYS',
  'CONFIG_DASHBOARD_STORE_PATH',
  'HCAPTCHA_SITE_KEY',
  'HCAPTCHA_SECRET_KEY',
  'CONTACT_RATE_LIMIT_WINDOW_MS',
  'CONTACT_RATE_LIMIT_MAX',
  'CONTACT_IP_THROTTLE_WINDOW_MS',
  'CONTACT_IP_THROTTLE_MAX',
  'CONTACT_IP_BLOCK_DURATION_MS',
  'CONTACT_BLOCKED_AGENTS',
  'CONTACT_SUSPECT_AGENTS'
];

for (const key of CLEAN_TEST_ENV_KEYS) {
  delete process.env[key];
}

for (const [key, value] of Object.entries(REQUIRED_ENV)) {
  process.env[key] = value;
}

process.env.FLAG_PERSONALIZATION = 'true';
process.env.FLAG_RENTGUY_INTEGRATION = 'true';
process.env.FLAG_SEVENSA_INTEGRATION = 'true';
process.env.FLAG_TELEMETRY = 'true';
